name: wol-api

services:
  backend:
    networks:
        - wol-api-network
    volumes:
      - ./backend:/home/appuser
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 8000:8000
  
  db:
    networks:
      - wol-api-network
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    volumes:
       - postgres-db:/data/postgres

volumes:
  postgres-db:
    driver: local

networks:
  wol-api-network:
