name: wol-api

services:
  backend:
    networks:
      - wol-api-network
    volumes:
      - ./backend:/home/appuser
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    depends_on:
      - db
    ports:
      - 8000:8000

  db:
    networks:
      - wol-api-network
    image: postgres:latest
    environment:
      POSTGRES_DB: wol-api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/data/postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-db:
    driver: local

networks:
  wol-api-network:
